#!/usr/bin/env python3
"""Minimal DuckDB worker for the structured-reasoning fit bench.

This file intentionally imports no Canario package code.  The parent process binds only
this worker, a dedicated DuckDB virtualenv, and private scratch into bubblewrap.
"""

from __future__ import annotations

import json
import math
import sys
import threading
import time
from decimal import Decimal
from pathlib import Path

import duckdb

PROJECTION_FORMAT = "canario.structured_projection.v1"
RESULT_FORMAT = "canario.structured_query_result.v1"


def fail(message: str, code: int = 2) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(code)


def canonical_value(value: object) -> dict[str, object]:
    if value is None:
        return {"type": "null"}
    if isinstance(value, bool):
        return {"type": "boolean", "value": value}
    if isinstance(value, int) and not isinstance(value, bool):
        return {"type": "integer", "value": str(value)}
    if isinstance(value, Decimal):
        return {"type": "number", "value": str(value)}
    if isinstance(value, float):
        if not math.isfinite(value):
            fail("non-finite result")
        return {"type": "number", "value": repr(value)}
    if isinstance(value, str):
        return {"type": "string", "value": value}
    if isinstance(value, bytes):
        return {"type": "bytes", "hex": value.hex()}
    if hasattr(value, "isoformat"):
        return {"type": "datetime", "value": str(value.isoformat())}
    fail(f"unsupported result type: {type(value).__name__}")
    raise AssertionError


def result_size(value: object) -> int:
    return len(json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8"))


def load_projection(path: Path) -> dict[str, object]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        fail(f"projection read failed: {exc}")
    if not isinstance(value, dict) or value.get("format") != PROJECTION_FORMAT:
        fail("invalid projection format")
    if not isinstance(value.get("sheets"), list) or not isinstance(value.get("cells"), list):
        fail("projection missing sheets/cells")
    return value


def cell_parts(cell: dict[str, object]) -> list[object]:
    value = cell.get("value")
    if not isinstance(value, dict):
        fail("cell missing value")
    kind = value.get("kind")
    text = None
    integer = None
    number = None
    boolean = None
    datetime = None
    formula = None
    if kind in {"string", "datetime", "formula", "error"}:
        text = str(value.get("text"))
    elif kind in {"integer", "number"}:
        text = str(value.get("decimal"))
    elif kind == "boolean":
        boolean = bool(value.get("value"))
        text = "true" if boolean else "false"
    elif kind != "blank":
        fail(f"unknown cell kind {kind!r}")
    if kind == "integer":
        candidate = int(str(value.get("decimal")))
        if -(2**63) <= candidate <= 2**63 - 1:
            integer = candidate
        number = float(candidate)
    elif kind == "number":
        number = float(Decimal(str(value.get("decimal"))))
    elif kind == "datetime":
        datetime = text
    elif kind == "formula":
        formula = text
    return [
        kind,
        text,
        integer,
        number,
        boolean,
        datetime,
        formula,
        str(cell.get("address")),
        str(cell.get("data_type")),
        str(cell.get("number_format")),
    ]


def _insert_rows_batched(
    con: duckdb.DuckDBPyConnection,
    table: str,
    rows: list[list[object]],
    *,
    chunk_rows: int = 64,
) -> None:
    """Insert trusted deterministic projection rows with bounded round trips.

    DuckDB's Python ``executemany`` performs materially more interpreter/driver work for
    this wide bench relation than a bounded multi-row VALUES insert.  The SQL shape here
    is generated only from trusted integer dimensions and the table name generated by
    this module; source values remain bound parameters.
    """

    if not rows:
        return
    width = len(rows[0])
    if width <= 0 or any(len(row) != width for row in rows):
        fail("projection row width mismatch")
    one_row = "(" + ",".join("?" for _ in range(width)) + ")"
    for offset in range(0, len(rows), chunk_rows):
        chunk = rows[offset : offset + chunk_rows]
        sql = f"INSERT INTO {table} VALUES " + ",".join(one_row for _ in chunk)
        params = [value for row in chunk for value in row]
        con.execute(sql, params)


def create_projection(con: duckdb.DuckDBPyConnection, projection: dict[str, object]) -> None:
    sheets = projection["sheets"]
    cells = projection["cells"]
    assert isinstance(sheets, list) and isinstance(cells, list)
    by_row: dict[tuple[int, int], dict[int, dict[str, object]]] = {}
    for raw in cells:
        if not isinstance(raw, dict):
            fail("malformed cell")
        by_row.setdefault((int(raw["sheet_ordinal"]), int(raw["row"])), {})[int(raw["column"])] = raw
    con.execute("BEGIN TRANSACTION")
    try:
        con.execute(
            "CREATE TABLE projection_sheets(ordinal BIGINT PRIMARY KEY,name VARCHAR,state VARCHAR,max_row BIGINT,max_column BIGINT,merged_ranges_json VARCHAR)"
        )
        sheet_rows: list[list[object]] = []
        for raw_sheet in sheets:
            if not isinstance(raw_sheet, dict):
                fail("malformed sheet")
            ordinal = int(raw_sheet["ordinal"])
            max_row = int(raw_sheet["max_row"])
            max_column = int(raw_sheet["max_column"])
            sheet_rows.append(
                [
                    ordinal,
                    str(raw_sheet["name"]),
                    str(raw_sheet["state"]),
                    max_row,
                    max_column,
                    json.dumps(raw_sheet.get("merged_ranges", []), ensure_ascii=False, sort_keys=True, separators=(",", ":")),
                ]
            )
            column_defs = ["row_index BIGINT PRIMARY KEY"]
            for column in range(1, max_column + 1):
                prefix = f"c{column}"
                column_defs.extend(
                    [
                        f"{prefix}_kind VARCHAR",
                        f"{prefix}_text VARCHAR",
                        f"{prefix}_integer BIGINT",
                        f"{prefix}_number DOUBLE",
                        f"{prefix}_boolean BOOLEAN",
                        f"{prefix}_datetime VARCHAR",
                        f"{prefix}_formula VARCHAR",
                        f"{prefix}_address VARCHAR",
                        f"{prefix}_data_type VARCHAR",
                        f"{prefix}_number_format VARCHAR",
                    ]
                )
            table = f"sheet_{ordinal}_rows"
            con.execute(f"CREATE TABLE {table}({','.join(column_defs)})")
            materialized_rows: list[list[object]] = []
            for row_index in range(1, max_row + 1):
                row_values: list[object] = [row_index]
                row = by_row[(ordinal, row_index)]
                for column in range(1, max_column + 1):
                    row_values.extend(cell_parts(row[column]))
                materialized_rows.append(row_values)
            _insert_rows_batched(con, table, materialized_rows)
        _insert_rows_batched(con, "projection_sheets", sheet_rows)
        con.execute("COMMIT")
    except BaseException:
        try:
            con.execute("ROLLBACK")
        except Exception:
            pass
        raise

def setting_map(con: duckdb.DuckDBPyConnection) -> dict[str, str]:
    return {str(row[0]): str(row[1]) for row in con.execute("SELECT name,value FROM duckdb_settings()").fetchall()}


def harden(con: duckdb.DuckDBPyConnection, request: dict[str, object]) -> dict[str, object]:
    current = setting_map(con)
    required = [
        "enable_external_access",
        "autoinstall_known_extensions",
        "autoload_known_extensions",
        "lock_configuration",
    ]
    missing = [name for name in required if name not in current]
    if missing:
        fail(f"required DuckDB security settings missing: {missing}")
    con.execute("SET autoinstall_known_extensions = false")
    con.execute("SET autoload_known_extensions = false")
    con.execute("SET enable_external_access = false")
    current = setting_map(con)
    for optional in ("allow_community_extensions", "allow_unsigned_extensions"):
        if optional in current:
            con.execute(f"SET {optional} = false")
    limits = request.get("limits")
    if not isinstance(limits, dict):
        fail("request limits missing")
    memory_limit = str(limits.get("memory_limit", "256MB"))
    threads = int(limits.get("threads", 1))
    con.execute(f"SET memory_limit = '{memory_limit}'")
    con.execute(f"SET threads = {threads}")
    # Freeze configuration before any untrusted statement is parsed/executed.  DuckDB's
    # security documentation recommends locking settings after the trusted bootstrap.
    con.execute("SET lock_configuration = true")
    after = setting_map(con)
    for name in ("enable_external_access", "autoinstall_known_extensions", "autoload_known_extensions"):
        if after.get(name, "").lower() not in {"false", "0"}:
            fail(f"DuckDB security setting not effective: {name}={after.get(name)}")
    if after.get("lock_configuration", "").lower() not in {"true", "1"}:
        fail(f"DuckDB configuration lock not effective: {after.get('lock_configuration')}")
    return {
        "enable_external_access": after.get("enable_external_access"),
        "autoinstall_known_extensions": after.get("autoinstall_known_extensions"),
        "autoload_known_extensions": after.get("autoload_known_extensions"),
        "allow_community_extensions": after.get("allow_community_extensions"),
        "allow_unsigned_extensions": after.get("allow_unsigned_extensions"),
        "lock_configuration": after.get("lock_configuration"),
        "memory_limit": after.get("memory_limit"),
        "threads": after.get("threads"),
    }


def statement_type_name(statement: object) -> str:
    raw_type = getattr(statement, "type", None)
    name = getattr(raw_type, "name", None)
    if isinstance(name, str):
        return name.upper()
    text = str(raw_type)
    return text.rsplit(".", 1)[-1].upper()


def _execute_select(
    con: duckdb.DuckDBPyConnection,
    sql: str,
    *,
    max_rows: int,
    max_bytes: int,
    query_timeout_ms: int,
) -> dict[str, object]:
    statements = con.extract_statements(sql)
    if len(statements) != 1:
        fail("query must contain exactly one parsed statement")
    stype = statement_type_name(statements[0])
    if stype != "SELECT":
        fail(f"only SELECT statements are allowed; parsed type={stype}")

    finished = threading.Event()
    timed_out = threading.Event()

    def interrupt_after_budget() -> None:
        if finished.wait(query_timeout_ms / 1000.0):
            return
        timed_out.set()
        try:
            con.interrupt()
        except Exception:
            # The parent process also retains a hard process wall-clock bound.
            pass

    watchdog = threading.Thread(target=interrupt_after_budget, name="duckdb-query-watchdog", daemon=True)
    started = time.monotonic()
    watchdog.start()
    try:
        cursor = con.execute(sql)
        columns = [str(item[0]) for item in cursor.description]
        rows: list[list[object]] = []
        while True:
            chunk = cursor.fetchmany(min(256, max_rows + 1 - len(rows)))
            if not chunk:
                break
            for row in chunk:
                if len(rows) >= max_rows:
                    fail("result row limit exceeded")
                rows.append([canonical_value(value) for value in row])
                deterministic_probe = {
                    "format": RESULT_FORMAT,
                    "columns": columns,
                    "rows": rows,
                    "row_count": len(rows),
                    "truncated": False,
                }
                if result_size(deterministic_probe) > max_bytes:
                    fail("result byte limit exceeded")
    except Exception:
        if timed_out.is_set():
            fail("query exceeded execution budget")
        raise
    finally:
        finished.set()
        watchdog.join(timeout=0.25)
    if timed_out.is_set():
        fail("query exceeded execution budget")
    deterministic = {
        "format": RESULT_FORMAT,
        "columns": columns,
        "rows": rows,
        "row_count": len(rows),
        "truncated": False,
    }
    import hashlib

    digest = hashlib.sha256(
        (json.dumps(deterministic, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8")
    ).hexdigest()
    return {
        **deterministic,
        "engine": "duckdb",
        "result_sha256": digest,
        "query_duration_ms": round((time.monotonic() - started) * 1000, 3),
        "query_watchdog_fired": timed_out.is_set(),
    }


def main() -> int:
    if len(sys.argv) != 3:
        fail("usage: worker projection.json request.json")
    projection = load_projection(Path(sys.argv[1]))
    request = json.loads(Path(sys.argv[2]).read_text(encoding="utf-8"))
    if not isinstance(request, dict):
        fail("invalid request")
    limits = request.get("limits")
    if not isinstance(limits, dict):
        fail("request limits missing")
    max_rows = int(limits.get("max_rows", 1000))
    max_bytes = int(limits.get("max_bytes", 1000000))
    query_timeout_ms = int(limits.get("query_timeout_ms", 2000))
    if query_timeout_ms <= 0:
        fail("query_timeout_ms must be positive")

    con = duckdb.connect(database=":memory:")
    try:
        security = harden(con, request)
        security["query_timeout_ms"] = query_timeout_ms
        bootstrap_started = time.monotonic()
        create_projection(con, projection)
        bootstrap_duration_ms = round((time.monotonic() - bootstrap_started) * 1000, 3)
        version = con.execute("SELECT version()").fetchone()[0]
        runtime = {
            "version": str(version),
            "python_package_version": str(getattr(duckdb, "__version__", "unknown")),
        }

        sql = request.get("sql")
        queries = request.get("queries")
        if isinstance(sql, str) and sql.strip() and queries is None:
            result = _execute_select(
                con,
                sql,
                max_rows=max_rows,
                max_bytes=max_bytes,
                query_timeout_ms=query_timeout_ms,
            )
            result["runtime"] = runtime
            result["security"] = security
            result["bootstrap_duration_ms"] = bootstrap_duration_ms
            result["projection_materializations"] = 1
            print(json.dumps(result, ensure_ascii=False, sort_keys=True, separators=(",", ":")))
            return 0

        if isinstance(queries, list) and sql is None:
            if not queries:
                fail("batch request must contain at least one query")
            if len(queries) > 128:
                fail("batch request exceeds query-count bound")
            seen: set[str] = set()
            results: list[dict[str, object]] = []
            for raw in queries:
                if not isinstance(raw, dict):
                    fail("batch query entry must be an object")
                query_id = raw.get("query_id")
                query_sql = raw.get("sql")
                if not isinstance(query_id, str) or not query_id or query_id in seen:
                    fail("batch query_id must be unique non-empty string")
                if not isinstance(query_sql, str) or not query_sql.strip():
                    fail("batch query SQL must be non-empty string")
                seen.add(query_id)
                result = _execute_select(
                    con,
                    query_sql,
                    max_rows=max_rows,
                    max_bytes=max_bytes,
                    query_timeout_ms=query_timeout_ms,
                )
                results.append({"query_id": query_id, "result": result})
            payload = {
                "format": "canario.duckdb_query_batch_result.v1",
                "engine": "duckdb",
                "runtime": runtime,
                "security": security,
                "bootstrap_duration_ms": bootstrap_duration_ms,
                "projection_materializations": 1,
                "query_count": len(results),
                "queries": results,
            }
            print(json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")))
            return 0

        fail("request must provide exactly one of sql or queries")
        raise AssertionError
    except Exception as exc:
        fail(f"{type(exc).__name__}: {exc}")
    finally:
        con.close()


if __name__ == "__main__":
    raise SystemExit(main())
